name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          environment: Cloudflare-pages
          secrets: CLOUDFLARE_API_TOKEN
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: bunx astro build
          command: pages deploy ./dist --project-name=${{ secrets.CF_PAGES_PROJECT_NAME }}
