name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Cloudflare-pages
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: npm
          preCommands: npx astro build --mode production
          command: pages deploy ./dist --project-name=${{ secrets.CF_PAGES_PROJECT_NAME }}
